async function main() {
  try {
  } catch (err) {
    console.log(err, "err")
  }
}

// @ts-ignore
await main()
