async function main() {
  try {
  } catch (err) {
    console.log(err)
  }
}

// @ts-ignore
await main()
console.log("done")
